sonar.projectKey=IETI-2026_backend
sonar.organization=ieti-2026
sonar.projectName=backend

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=src/**/*.spec.ts,test/**/*.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=\
  src/**/*.spec.ts,\
  test/**/*.ts,\
  src/**/*.module.ts,\
  src/main.ts,\
  src/app.module.ts,\
  src/database/**,\
  src/database/entities/index.ts,\
  src/**/*.repository.ts
